### ISSUE TITLE
White flash when switching between NOW and TODAY

### ISSUE THREAD

**Issue by arun057** [marineb/feelio-ios-app#2]
Steps to reproduce:

1. Launch app
2. Swipe right to show sidebar 
3. Tap main window to go back to the NOW screen
4. Tap TODAY 

You will see a white flash on the screen before the TODAY page loads.

**Comment by marineb** [comment]
Thank you! Fixed in version 0.1, build 3.

**Comment by arun057** [comment]
Looks like the latest version 0.1-3 fixes this
