### ISSUE TITLE
Type Contrast & Hierarchy

### ISSUE THREAD

**Issue by carolinayux** [marineb/feelio-ios-app#3]
increase contrast between bg color and copy. Also, bump up time size to create more of a hierarchy/differentiation between the three assets: Time, Clothing Suggestion, Temp Details.

**Comment by marineb** [comment]
Made some improvements on this in v0.1, build 5. But waiting to make other improvements to push the new app version to everyone. You'll have to let me know what you think!  ☺️

Ultimately, planning to implement [3 themes](https://github.com/marineb/feelio-ios-app/issues/8).

**Comment by marineb** [comment]
Closing for now. Feel free to reopen once you've been able to assess!

**Comment by carolinayux** [comment]
Very cool; can't wait to see new release! Not sure what you were thinking with 3 themes idea, but I keep thinking about how it would look if the "time of day" color themes (following a "later, much later, waaay later" model) involved the user interacting with the screen by either a horizontal or vertical swipe. So, for example, if a user is looking at the screen at 6am, the color theme in the center of the screen would reflect said time, but users would be able to see hint of midday sun colors towards the right hand side of the screen. Like a horizon, I guess. The other idea would follow the same model but run vertically. The downside of these is that you wouldn't have the three times immediately visible on one screen BUT you could actually merge both screens. 

I have no clue if that makes any sense or if you're even looking for opinionated people's contribution!! ;) Rough sketch attached.

C.





www.carolinapaula.com

(This was written on a tiny keyboard, so please forgive embarrassing typos.)
